source 'https://github.com/wgModularization/WGModulSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'wgPersonInfoKit_Example' do
  pod 'wgPersonInfoKit', :path => '../'

end
